### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by entering** [beberlei/DoctrineExtensions#105]
I use doctrine extensions, and is nice to have a tag that is stable to fix to it on composer, is possible to create a tag from stable code? (the last tag is from a year ago)

**Comment by stevelacey** [comment]
Working on this, my current plan is to merge all of the PR's scattered across the repo and forks to form a 0.3 release, and moving forward, a 1.0 release that strips legacy components such as the Paginator etc which are now either redundant or available in Doctrine core.

**Comment by stevelacey** [comment]
https://github.com/beberlei/DoctrineExtensions/blob/master/README.md

**Comment by csarrazi** [comment]
Good luck! :)

**Comment by stevelacey** [comment]
@entering @csarrazi @KamilKopaczyk done!

**Comment by entering** [comment]
thanks
