### ISSUE TITLE
PaginationAdapter fails when result result set empty

### ISSUE THREAD

**Issue by MrHash** [beberlei/DoctrineExtensions#12]
getItems() in PaginationAdapter.php calls createWhereInQuery() when $ids array is empty causing SQL exception because the WHERE/IN() clause is malformed.

Possible solution is to add this into Paginate::createWhereInQuery()

if(empty($ids)) return $query;

**Comment by stevelacey** [comment]
@MrHash I realise this was a while ago, but just cleaning up this repo. I am happy to merge fixes for the paginator into the 0.3, but it is no longer actively supported – I recommend switching to the paginator available in Doctrine core if you're still having issues.
