### ISSUE TITLE
Couldn't find a license

### ISSUE THREAD

**Issue by LewisW** [beberlei/DoctrineExtensions#126]
This package has no license or terms of use explicitly mentioned, from what I could find. This is a problem since legally it's still closed source, which poses a legal risk to all those that use it.

Any chance you could associate a license to it?

Thanks.

**Comment by stevelacey** [comment]
https://github.com/beberlei/DoctrineExtensions/commit/fb4e204f14d39eee02a6d443da1831d2f12c7890
