### ISSUE TITLE
Combine two or more extensions

### ISSUE THREAD

**Issue by RempelOliveira** [beberlei/DoctrineExtensions#132]
How to combine two or more extensions like the example?

Query:
GROUP_CONCAT(CONCAT_WS(' - ', field_one, field_two))

**Comment by stevelacey** [comment]
@RempelOliveira I am not sure this is supported, but it would be good if it was @beberlei @webdevilopers do you know better?

**Comment by webdevilopers** [comment]
I tried something similar but I think it is not possible per se. The `SqlWalker` defines an format and expected placeholders e.g. `SEPARATOR` etc. - I guess you have to write a custom extension for these use cases.

Maybe there is a solution to check if expressions inside  the `SqlWalker` is an `instance of` `\Doctrine\ORM\Query\SqlWalker` and then parse the Sql recursively.

But guess that is a tough task and maybe BC.

**Comment by nitso** [comment]
There is similar SO question if I understood the issue correctly: http://stackoverflow.com/questions/14505105/nested-dql-user-defined-functions

So it could be a bug in extension definition.

**Comment by laufhannes** [comment]
Just for anyone who's stumbling upon this issue and wants to use nested functions: At least for `YEAR(FROM_UNXTIME(...))` (and `MONTH`) the combination **does** work. (at least for v1.0.12 and v2.5.5 of doctrine/orm)

So, probably only a few functions are affected.

**Comment by Spawnrad** [comment]
Is it possible to combine GROUP_CONCAT(WHEN CASE ... )
please?

**Comment by stevelacey** [comment]
I am going to close this as very very inactive – various functions can be combined – it's largely based on how strictly the wrapping function was written – if there are problems with any particular function, pull requests are welcome
