### ISSUE TITLE
opening this repository to other contributors and/or see to be maintain by doctrine devs 

### ISSUE THREAD

**Issue by allan-simon** [beberlei/DoctrineExtensions#133]
Hello 

You stated that you no longer maintain this project, which i understand perfectly, however issues and PR start to stack here, and people starts to create fork, but the problem is there's no "official" fork and the fixes will be dispatch across a dozen of forks with none containing them all which would be a great pitiy

would it possible for you to find somebody interesting into taking the maintenance of this repository ? by opening a ticket so that people who are interested can propose themselves ?

Thanks a lot for all what you've already done :)

**Comment by guilhermeaiolfi** [comment]
Damn, not even a reply? @beberlei

**Comment by beberlei** [comment]
The question is who to give commit access to this repository, there is no single outstanding committer that I can see would want to take this task up. Would someone want to maintain this repository? Please step up.

**Comment by mikeSimonson** [comment]
to the doctrine team or the phpleague ?

**Comment by beberlei** [comment]
it will not be moved to Doctrine project, because we cannot and don't want to maintain it (timewise)

**Comment by webdevilopers** [comment]
Since there are many single repo versions e.g. by @WiredMedia, @OroCRM or @kassner it would be great to have a global solution. :+1:

**Comment by stevelacey** [comment]
@beberlei I'd be interested – I made the @WiredMedia fork.

**Comment by stevelacey** [comment]
I am maintaining this now, PR away! :smile:

**Comment by webdevilopers** [comment]
Does the following repo feature any resources that would make sense for this repo?
https://github.com/Atlantic18/DoctrineExtensions

Maybe contributors like @l3pp4rd are interested.


There are also many `MySQL` functions already featured in:
https://github.com/orocrm/doctrine-extensions/tree/master/src/Oro/ORM/Query/AST/Platform/Functions/Mysql
maintained by @x86demon

And some very interesting `PostgreSQL` functions we do not have it all in this repo so far:
https://github.com/orocrm/doctrine-extensions/tree/master/src/Oro/ORM/Query/AST/Platform/Functions/Postgresql

**Comment by stevelacey** [comment]
@webdevilopers not sure about Atlantic, seems to fit a very different need albeit named similarly, interested in merging efforts with @x86demon and that library though, seems very similar.
