### ISSUE TITLE
Platform support for UNIX_TIMESTAMP and FROM_UNIXTIME

### ISSUE THREAD

**Issue by andig** [beberlei/DoctrineExtensions#135]
Could these be added as DBAL extensions? Would be glad to help but would need a pointer where to get started.

**Comment by stevelacey** [comment]
@andig absolutely, in fact, they've both already been implemented – they're just in PR's we can't merge... if you wanted to grab what they've done and submit a new PR that does merge, that would be fantastic.

https://github.com/beberlei/DoctrineExtensions/pull/97
https://github.com/beberlei/DoctrineExtensions/pull/122

**Comment by nimasdj** [comment]
@stevelacey why can't you merge them?

**Comment by andig** [comment]
Merge conflict. We simply need to put up a new pr.

**Comment by pitpit** [comment]
Hi,
I've done a new PR for #97 here : https://github.com/beberlei/DoctrineExtensions/pull/176
