### ISSUE TITLE
Incompatibility with Symfony 2.6

### ISSUE THREAD

**Issue by mbyta** [beberlei/DoctrineExtensions#145]
Hi,

When I run this command:
`composer require beberlei/DoctrineExtensions`

I get this message

`Could not find package beberlei/DoctrineExtensions at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

NB: I use Symfony 2.6 for my project

Do you know how can I fix this?

Thanks

**Comment by stevelacey** [comment]
Not sure why this is happening, Composer can't seem to detect the latest stable – I am wondering if it is because of the `v` prefix on the tags, which is "supposed" to make no difference :confused:

Anyway, the following should work for you:

```sh
composer require beberlei/DoctrineExtensions "~1.0"
```

**Comment by mbyta** [comment]
Yes, it works

Thanks Steve

**Comment by xabbuh** [comment]
FYI, this was an issue in Composer that has been fixed with composer/composer#3917. So `composer require beberlei/DoctrineExtensions` should work again.

**Comment by mbyta** [comment]
Got it !

Thank you all !!
