### ISSUE TITLE
abstract ENUM & SET types

### ISSUE THREAD

**Issue by marc-mabe** [beberlei/DoctrineExtensions#150]
As of the types `ENUM` & `SET` are often requested how about the following:

_Enum:_
- Add an `abstract EnumType` that can be extended and linked to an own enumeration definition class like definable by https://github.com/marc-mabe/php-enum.
- Map this to the native `ENUM` type on MySQL and use an integer based type on others.

``` php
namespace DoctrineExtensions\Types;
use Doctrine\DBAL\Platforms\AbstractPlatform,
    Doctrine\DBAL\Types\Type,
    MabeEnum\Enum;

abstract class EnumType extends Type
{
    /**
     * @return string The enumeration class
     */
    abstract public function getEnumeration();

    public function getName()
    {
        return str_replace('\\', '_', $this->getEnumeration());
    }

    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        if ($platform instanceof MySql) {
            $enumeration = $this->getEnumeration();
            return 'ENUM(' . implode(',', $enumeration::getConstants()) . ')';
        }
        return $platform->getIntegerTypeDeclarationSQL($fieldDeclaration);
    }

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        if ($value === null) {
            return null;
        }

        $enumeration = $this->getEnumeration();
        $enumerator = $enumeration::get($value);
        return ($platform instanceof MySql) ? $enumerator->getValue() : $enumerator->getOrdinal();
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        if ($value === null) {
            return null;
        }

        $enumeration = $this->getEnumeration();
        return ($platform instanceof MySql) ? $enumeration::get($value) : $enumeration::getByOrdinal();
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return !($platform instanceof MySql);
    }
}
```

_SET:_
- Same as ENUM but use https://github.com/marc-mabe/php-enum/blob/master/src/EnumSet.php

Thoughts ?

**Comment by stevelacey** [comment]
Yes this would be neat, though I would prefer separate classes or some other form of toggle than 'if MySQL' in each function.

Sorry I took a year to reply 😐

**Comment by marc-mabe** [comment]
> I would prefer separate classes ...

Does that mean you have to use another class if you want to switch the DB?

> ... or some other form of toggle than 'if MySQL' in each function

It also would be possible to just add configuration property for using the value or the ordinal number but personally I would prefer to have the `if MySQL` -condition at least on declaration.

# Value vs. Ordinal Number

## Value:
* better readable by humans on platforms without native enumeration support
* independent of defined order of enumerators (in case of changes)

## Ordinal Number
* supports all types of enumerator values - not just strings and additionally on native MySQL enumerations `,` can't be used
* less network traffic

**Comment by stevelacey** [comment]
@marc-mabe I still think this would be a great contribution but I am going to close this due to inactivity, feel free to submit a pull request if you ever implement this 😄
