### ISSUE TITLE
TestCase CarbonDateTest::testDateGetter should compare only date part.

### ISSUE THREAD

**Issue by manish-tal** [beberlei/DoctrineExtensions#169]
A scenario which failed:
> DoctrineExtensions\Tests\Types\CarbonDateTest::testDateGetter
> Failed asserting that two DateTime objects are equal.
> --- Expected
> +++ Actual
> @@ @@
> -2015-01-01T10:09:16+0000
> +2015-01-01T10:09:15+0000

which I believe is incorrect. It occurred because test case `CarbonDateTest::testDateGetter` is asserting DateTime object should be equal. But in this case checking on time is insignificant.

**Comment by stevelacey** [comment]
Yeah it's a race condition, just re-run the tests. Bonus points if you actually want to fix it.

**Comment by manish-tal** [comment]
Created pull request for same #170
