### ISSUE TITLE
DQL function in FROM and JOIN clauses

### ISSUE THREAD

**Issue by fracasula** [beberlei/DoctrineExtensions#172]
Hi there,

I've been trying to write a custom DQL function so that I can call it in the `FROM` clause for example or in a `INNER JOIN`. As far as I could see I'm not sure it's doable though. Can you please confirm if it is?

This is how my query looks like in native MySQL:

    SELECT t1.* FROM my_table PARTITION(my_partition_name) t1
    INNER JOIN another_table PARTITION(another_partition) t2 ON t1.whatever = t2.whatever;

**Comment by stevelacey** [comment]
Sorry no one got back to you on this, I am going to assume you've worked out whether this possible or not by now – my guess would be no (PR welcome though)
