### ISSUE TITLE
Oracle. Can't group by a function

### ISSUE THREAD

**Issue by nitso** [beberlei/DoctrineExtensions#175]
DQL example:

```
SELECT t.status, count(t.id) cnt, DAY(t.createdAt) sday 
FROM Status t GROUP BY t.status, sday
```

Error received: 

```
ORA-00904: "SCLR2": invalid identifier
```

DQL example with function in group by expression:

```
SELECT t.status, count(t.id) cnt, DAY(t.createdAt) sday 
FROM Status t GROUP BY t.status, DAY(t.createdAt)
```

Error received: 

```
[Semantical Error] line 0, col 96 near 'DAY(t.create': Error: 
Cannot group by undefined identification or result variable.
```

So, Oracle does not support alias in `group by` expression. An alias should be exposed or function should be allowed to use in `group by` expression

**Comment by stevelacey** [comment]
@nitso a bit late to the party but I recognised your handle, your last contribution was good, any chance you can have a crack at solving this?

**Comment by nitso** [comment]
I'll do my best whenever I come back to this issue :)

**Comment by stevelacey** [comment]
@nitso I am going to close this due to inactivity, but feel free to submit that pull request sometime 😄
