### ISSUE TITLE
Add Type function

### ISSUE THREAD

**Issue by enumag** [beberlei/DoctrineExtensions#195]
Hi, I'd like to add a TYPE function based on [this gist](https://gist.github.com/jasonhofer/8420677) from @jasonhofer. It is not database specific so I'm not sure where to put it or if it is even wanted in this package.

Of course if Doctrine has a different way to get to the discriminator field in DQL, I'd like to know.

**Comment by stevelacey** [comment]
Not sure if this library is really the place for this, but I imagine somewhere like `DoctrineExtensions\Query\AST\Functions\TypeFunction` would be the place to put it.
