### ISSUE TITLE
Implement aggregate expressions

### ISSUE THREAD

**Issue by FlashBlack** [beberlei/DoctrineExtensions#199]
Is it possible here to implement the handler on [Aggregate Expressions](http://www.postgresql.org/docs/9.4/static/sql-expressions.html#SYNTAX-AGGREGATES) ?

Like:

```sql
SELECT ... COUNT(..) FILTER ( WHERE filter_clause )
```

**Comment by stevelacey** [comment]
I expect this relates to #132, which is unsupported, and yeah, difficult – I am up for reviewing a pull request that implements it if you're feeling brave enough :smile:

**Comment by FlashBlack** [comment]
I solved this: #202
