### ISSUE TITLE
PaginationAdapter: query with "group by" throws an exception

### ISSUE THREAD

**Issue by mbaumgartl** [beberlei/DoctrineExtensions#2]
If a query with a "group by" expression is used with the PaginationAdapter, a \Doctrine\ORM\NonUniqueResultException is thrown in \Doctrine\ORM\Internal\Hydration\SingleScalarHydrator.

**Comment by stevelacey** [comment]
@mbaumgartl @timdev I am happy to merge fixes for the paginator into the 0.3, but it is no longer actively supported – I recommend switching to the paginator available in Doctrine core if you're still having issues.
