### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by marcoalbarelli** [beberlei/DoctrineExtensions#206]
Hi
I wanted to know if there are known problems with PHP7
We're currently using this bundle along with Doctrine 2.5.1 and so far everything works fine. 
We're planning the move to PHP7 and preliminary tests don't show any problem.

I ran the tests in the bundle in a PHP7 environment and they are green.

Basically I'm just checking to see if I overlooked something

**Comment by stevelacey** [comment]
Travis is set up to test against PHP7 and it passes (although our test
coverage is poor), afaik everything works.

On Wednesday, 1 June 2016, Marco Albarelli <notifications@github.com> wrote:

> Hi
> I wanted to know if there are known problems with PHP7
> We're currently using this bundle along with Doctrine 2.5.1 and so far
> everything works fine.
> We're planning the move to PHP7 and preliminary tests don't show any
> problem.
>
> I ran the tests in the bundle in a PHP7 environment and they are green.
>
> Basically I'm just checking to see if I overlooked something
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/beberlei/DoctrineExtensions/issues/206>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AARq-6EfQQfCgWtV6F6w8Jlkn6o4kSclks5qHasygaJpZM4Irs8q>
> .
>


-- 

Steve Lacey steve.ly / @stevelacey <http://www.twitter.com/stevelacey> /
steve@stevelacey.net
