### ISSUE TITLE
week function in Sqlite

### ISSUE THREAD

**Issue by anyx** [beberlei/DoctrineExtensions#207]
Looks like now it is just copy-paste from Mysql and not working, obviously.
I started to write pr for this, but i don't know, how correctly reproduce mysql behavior when second argument was not passed (sun-sat week).

**Comment by stevelacey** [comment]
Examples of what does and doesn't work?

**Comment by anyx** [comment]
Sqlite does not have function "week". Any call of that function will throw exception.

**Comment by stevelacey** [comment]
https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_week

**Comment by anyx** [comment]
I talk about **Sqlite**

https://github.com/beberlei/DoctrineExtensions/blob/master/src/Query/Sqlite/Week.php#L16

**Comment by stevelacey** [comment]
Ah, I see. A PR fixing this and omitting support for the second argument would still be an improvement.

**Comment by anyx** [comment]
#213

**Comment by stevelacey** [comment]
thanks!
