### ISSUE TITLE
SIN, COS, ACOS for PGSQL

### ISSUE THREAD

**Issue by juandpr** [beberlei/DoctrineExtensions#208]
Why are not the functions ACOS, COS, SIN and so, available for PostgreSQL, since that Database includes them ?

**Comment by stevelacey** [comment]
Pull requests welcome

On Friday, 1 July 2016, Juan Dalmasso <notifications@github.com> wrote:

> Why are not the functions ACOS, COS, SIN and so, available for PostgreSQL,
> since that Database includes them ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/beberlei/DoctrineExtensions/issues/208>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AARq-3DFWgP3ilEzVzoXzSRGEjpGRx4mks5qRKGNgaJpZM4JC0p2>
> .
>


-- 

Steve Lacey steve.ly / @stevelacey <http://www.twitter.com/stevelacey> /
steve@stevelacey.net
