### ISSUE TITLE
[Feature request] MySQL: EXP(x)

### ISSUE THREAD

**Issue by christiandreher** [beberlei/DoctrineExtensions#216]
MySQL supports the exponential function f(x)=e^x with EXP(X) (http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html#function_exp).
I know that you already provide a POWER function, but it would be prettier if you'd not have to define e inside the code. I can't estimate the afford to implement this feature, but I think that this would just be a new class extending POWER in such way that POWER(base, exponent) will become EXP(exponent) with base := 2,7......

**Comment by stevelacey** [comment]
I don't follow, but the function should be implemented in a way that the DQL looks like the SQL wherever possible.
