### ISSUE TITLE
Migration diff command always add migration for custom type CarbonDateTime

### ISSUE THREAD

**Issue by josecelano** [beberlei/DoctrineExtensions#224]
When I execute migrations diff command I always get SQL code to alter columns with `CarbonDateTime`.

I have the same problem with all custom types not only `CarbonDateTime`. I have opened an issue in doctrine dbal repo:

https://github.com/doctrine/dbal/issues/2506#issuecomment-247359947

It seems I can fix the problem using `getSqlDeclaration` in my custom types clases, but I think there must be a better solution to that problem than adding a method like:

```
    /**
     * @param array            $fieldDeclaration
     * @param AbstractPlatform $platform
     * @return string
     */
    public function getSqlDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return sprintf('BINARY(%d) COMMENT \'(DC2Type:uuid)\'', $fieldDeclaration['length']);
    }
```

In fact, I should overwrite your classto your [CarbonDateTimeType](https://github.com/beberlei/DoctrineExtensions/blob/5e4eeb632b18da7a848b9b470ff1e688200c0d4e/src/Types/CarbonDateTimeType.php) class.

Does anybody know a better solution to this problem?

Thanks

**Comment by stevelacey** [comment]
@josecelano I do not know of a better solution, yours looks apt, a pull request implementing this on `CarbonDateTime` and anything else affected would be more than welcomed – bonus points for a test exercising the behaviour.

**Comment by stevelacey** [comment]
@josecelano any chance of a PR for this? Thanks!
