### ISSUE TITLE
LPAD is not working

### ISSUE THREAD

**Issue by hwaqar44** [beberlei/DoctrineExtensions#226]
$query = $queryBuilder->select(array(
            "LPAD(changeorder.code,4,'0') as code",
        ))->from('Application\Entity\ChangeOrders', 'changeorder');

Gives ERROR
[Syntax Error] line 0, col 196: Error: Expected known function, got 'LPAD'

**Comment by stevelacey** [comment]
Are you sure you registered the function correctly?

**Comment by stevelacey** [comment]
I don't have enough information to help so I am going to close this issue, afaik this works and you should double check your configuration – feel free to reply and @ me if you're still having issues, thanks! 😄

**Comment by hwaqar44** [comment]
In my configuration 
'lpad' => 'DoctrineExtensions\Query\Mysql\Lpad',
i had done that and in query i was using LPAD, 
But when i changed lpad to LPAD  it start working 
thanks for the reply
