### ISSUE TITLE
Add case sensitive functionality - REGEXP and REGEXP BINARY

### ISSUE THREAD

**Issue by matheusgontijo** [beberlei/DoctrineExtensions#238]
As described [in this link](http://stackoverflow.com/a/10315901/4854453) the expression `REGEXP` is case insensitive. However for case sensitive checking is necessary `REGEXP BINARY`.

Example:
`SELECT 'a' REGEXP 'A';` == 1
`SELECT 'a' REGEXP BINARY 'A';` == 0

**Comment by stevelacey** [comment]
@matheusgontijo pull request welcome :+1:
