### ISSUE TITLE
Aes*.php classes have wrong namespace

### ISSUE THREAD

**Issue by nicanaca0** [beberlei/DoctrineExtensions#251]
AesDecrypt.php and AesEncrypt.php are effect but no other classes seem to be (checked using grep)

Error from symfony when trying to use the Extension was:
`The file was found but the class was not in it, the class name or namespace probably has a typo.`

Namespace is:
`namespace BoaCompra\DoctrineExtensions\Query\Mysql;`

Should be:
`namespace DoctrineExtensions\Query\Mysql;`

**Comment by stevelacey** [comment]
Yes, a pull request to fix the namespace would be great
