### ISSUE TITLE
Issue while installing the extension with PHP 7.0.21

### ISSUE THREAD

**Issue by surinderpalsingh** [beberlei/DoctrineExtensions#258]
I got below error while installing the extension

`This package requires PHP 5.6.* but your PHP version (7.0.21) does not satisfy that requirement.`

Please advise me.

**Comment by stevelacey** [comment]
@surinderpalsingh are you sure this is coming from DoctrineExtensions?

The test suite runs against 7.0 and 7.1 on Travis so this should work.

**Comment by surinderpalsingh** [comment]
Yes and my PHP version is `php-7.0.21`

**Comment by stevelacey** [comment]
This package requires `>=5.3.2`, you're getting an error from a different package I think.

https://github.com/beberlei/DoctrineExtensions/blob/master/composer.json#L12

**Comment by surinderpalsingh** [comment]
I have downgraded my PHP version from 7.0.21 to 5.6.31  and it works.

**Comment by stevelacey** [comment]
Again, I don't think this is related to DoctrineExtensions – can you paste the full output of your `composer install`?

**Comment by surinderpalsingh** [comment]
It's your wish to CLOSE this issue and but I'm still facing this with PHP 7.0.21.

**Comment by stevelacey** [comment]
I don't think this is an issue related to this package – your error is coming from something else, many users run this on PHP 7.0 and 7.1, we test against this as well:

https://travis-ci.org/beberlei/DoctrineExtensions/builds/243564460

**Comment by stevelacey** [comment]
We don't, and never have had a `5.6.*` requirement, the library works on `5.3–7.1`

**Comment by surinderpalsingh** [comment]
I've deleted all my packages from composer.json and it works. It's definitely from another package. 
But it's weird that composer was giving me another package's error while installing this extension with command  `php composer.phar require beberlei/DoctrineExtensions` but it should not be. Even there is no information about another package to fix the issue. My apology.

**Comment by stevelacey** [comment]
Try doing a composer install or update without changing the composer.json, I expect the update will fail in a similar way.
