### ISSUE TITLE
probleme with date_diff.

### ISSUE THREAD

**Issue by xorgxx** [beberlei/DoctrineExtensions#261]
hi 
i use SF3.3, MySql 5.5, PHP 5.6 local windows, production linux
in local i dont have any probleme wiht this : 
```
        $qb = $this->createQueryBuilder ( 't' )
            ->update()
            ->set('t.dayLeft', "DATEDIFF(t.dateFinish, CURRENT_TIME())")
            ->getQuery ()
            ->execute()
        ;
```
but it simce thas in production it das not do the job.
cant you see any probleme?
Thank

**Comment by stevelacey** [comment]
What's the error?

**Comment by xorgxx** [comment]
das not do job on linux production but it do very well on windows dev mode local.

**Comment by xorgxx** [comment]
so i ded some test this morrning and : 

```
->set('t.dayLeft', 'DATEDIFF(t.dateFinish, CURRENT_TIME())')
```
if i change to this ->set('t.dayLeft', 3) it work very well on dev and prod.
dateFinish is datetime.

**Comment by xorgxx** [comment]
So find the probleme it was 
```
before : CURRENT_TIME
after  : CURRENT_DATE
```
Thank for your help.
