### ISSUE TITLE
"Class not found"-Errors. Class loading does not worrk?

### ISSUE THREAD

**Issue by victor-lund** [beberlei/DoctrineExtensions#263]
I'm using Slim 3 Framework and trying to load the extenstion by doing this.

 ```
$classLoader = new \Doctrine\Common\ClassLoader('DoctrineExtensions', __DIR__.'/vendor/beberlei/DoctrineExtensions');
$classLoader->register();
$ormConfig->addCustomStringFunction('DATE', 'DoctrineExtensions\Query\MySql\Date');
$em = EntityManager::create($dbParams, $ormConfig);
```
...and using it like this:
```

$dql = 'SELECT COUNT(u.id),
u.createdAt,
DATE(u.createdAt) AS groupDate 
CAST(u.createdAt as date) AS HIDDEN groupDateGrp 
FROM Entity\User u 
GROUP BY DATE(groupDateGrp) 
ORDER BY u.createdAt DESC
 ';

$query = $em->createQuery($dql);
$query->setParameters(['userId'=>$userId]);
$result = $query->getOneOrNullResult();
```

which gives me the error:
```
Class 'DoctrineExtensions\\Query\\Postgresql\\DateDiff' not found in file <webroot>/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php on row 3497
```
So, i guess the class loading does not work. I have tried to follow the instructions here:
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/dql-user-defined-functions.html
and here:
https://github.com/beberlei/DoctrineExtensions

What am I missing?

**Comment by stevelacey** [comment]
We don't have a `DoctrineExtensions\Query\Postegresql\DateDiff` class, so no idea where this has come from, I imagine you must be referencing this somewhere – it's not in your example above.

Another thing I can see that will trip you up is you're referencing the Mysql namespace with a capital S – it's `DoctrineExtensions\Query\Mysql\Date` with Mysql not MySql.

Either way I imagine we would know if DoctrineExtensions was incompatible with the Doctrine class loader, so I am going to close this, but feel free to continue asking questions if you think I can help.

**Comment by victor-lund** [comment]
Ahh, I posted the wrong error message. The real error message was 
```
Class 'DoctrineExtensions\\Query\\Postgresql\\Date' not found in file <webroot>/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php on row 3497`
```

Anyway, the non-capital "s" was indeed the issue here. Thanks!

**Comment by stevelacey** [comment]
🙌
