### ISSUE TITLE
DATEFORMAT: Set start of the week to Monday instead of Sunday

### ISSUE THREAD

**Issue by victor-lund** [beberlei/DoctrineExtensions#267]
Hello,
I have a method that groups data on weeks that looks something like this:
```
        $query = $em->getRepository("Entity\User")
            ->createQueryBuilder('u')
            ->select("
                ps.name as psName,
                DATEFORMAT(r.createdAt,'WW') AS rsCreatedAt,
                COUNT(psre.id) as psreCount,
                AVG(psre.degree) as avgSym
            ")
      ...etc
```

It's working fine with one exception: It appears as the week starts on sundays instead of mondays which is not what i want. I want the week to start on monday - is this possible?

**Comment by stevelacey** [comment]
@victor-lund are you asking how to adjust the behaviour of MySQL's DATEFORMAT function? I don't think this question has anything to do with the behaviour of DoctrineExtensions so I am going to close it – I suggest you refer to the MySQL docs and/or rethink your approach

**Comment by victor-lund** [comment]
This was solved using IW instead of WW (postgres syntax from formating datetime according to ISO 8601).
