### ISSUE TITLE
DATE() function in groupBy

### ISSUE THREAD

**Issue by Holicz** [beberlei/DoctrineExtensions#268]
Hi,

I am facing an issue with DATE() function and groupBy. Basically the function is not working in there.

`$queryBuilder->groupBy('DATE(p.createdAt)')`

goes into this

`[Semantical Error] line 0, col 119 near 'DATE(p.creat': Error: Cannot group by undefined identification or result variable.`

**Comment by stevelacey** [comment]
I expect this to work – people have used the `Day` (almost identical to `Date`) function as an example of a sqlWalker extension that can be used in groupBy.

Maybe try aliasing in the select as per one of the answers here:
https://stackoverflow.com/a/35596660
