### ISSUE TITLE
unable to upload on php7.1 due to notice

### ISSUE THREAD

**Issue by is3kk** [beberlei/DoctrineExtensions#270]
Hello,

I was unable to complete upload of an image when using sonata-admin on php7.1 . Problem i found was 

> Notice: A non well formed numeric value encountered 
> in vendor/comur/image-bundle/Comur/ImageBundle/Handler/UploadHandler.php at line 344

i fixed it by adding a line 
`$val =  substr($val, 0, -1);`

inside this function 
`function get_config_bytes($val) {

        $val = trim($val);

        $last = strtolower($val[strlen($val)-1]);

        $val =  substr($val, 0, -1);

        switch($last) {

            case 'g':

                $val *= 1024;

            case 'm':

                $val *= 1024;

            case 'k':

                $val *= 1024;

        }
        return $this->fix_integer_overflow($val);
    }`

and it works fine after this..  BTW i think it should be like *1024*1024 in case of Mb an so on, but nwm..

So maybe it helps someone else.

**Comment by stevelacey** [comment]
@is3kk cool story 😄 any reason you’re posting it on DoctrineExtensions? 🙃
