### ISSUE TITLE
Is FROM_UNIXTIME() support format?

### ISSUE THREAD

**Issue by JackNUMBER** [beberlei/DoctrineExtensions#274]
Hi! I recently tried to retrieve the year from a timestamp with `FROM_UNIXTIME(timestamp, '%Y')` but I got this error:
> [Syntax Error] line 0, col 30: Error: Expected Doctrine\ORM\Query\Lexer::T_CLOSE_PARENTHESIS, got ','

Is param are supported for the FROM_UNIXTIME() query function? ([ref documentation](https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_from-unixtime))

To bypass this issue I use this, it's more like a hack than a good practice: `YEAR(FROM_UNIXTIME(timestamp))`.

Symfony 3.3.9

Thanks!

**Comment by stevelacey** [comment]
@JackNUMBER it does not, pull requests welcome! 😀
