### ISSUE TITLE
implement WeekDay has an issue in Symfony 3

### ISSUE THREAD

**Issue by Carredas** [beberlei/DoctrineExtensions#278]
I Succeed to implement WeekDay with Symfony3. But i had to modidified a type in the namespace of the WeekDay.php file.
The name space is namespace DoctrineMgidExtensions\Query\Mysql; (See the Mgid)
But the repertory is DoctrineExtensions\Query\Mysql\WeekDay
When i modified the nameplace in the WeekDay.php file with namespace DoctrineExtensions\Query\Mysql; all was correct.
Of course in my config file i had put:
    orm:
        dql:
            string_functions:
                WEEKDAY: DoctrineExtensions\Query\Mysql\WeekDay
(Sorry for my english :()

**Comment by stevelacey** [comment]
@Carredas not sure where `DoctrineMgidExtensions` came from but not this project :) the namespace is correct in WeekDay.php
