### ISSUE TITLE
Show function use examples

### ISSUE THREAD

**Issue by roberto910907** [beberlei/DoctrineExtensions#280]
Sometimes it's necessary to see an example using the function, for example the original sql function `DATE_SUB("2017-06-15", INTERVAL 10 DAY)` is a little different as we use with this bundle `DATESUB(user.createdAt, 10, 'DAY')`. Maybe in README add a new section or a tooltip linked to funtion list section.

**Comment by stevelacey** [comment]
@roberto910907 pull requests welcome, most should match, but you're right, some don't, and maybe that should be fixed, or at least document ✌️
