### ISSUE TITLE
HP Fatal error:  Uncaught Error: Call to undefined method Doctrine\Common\ClassLoader::getName() in /vagrant/app/bootstrap.php.cache:2582

### ISSUE THREAD

**Issue by sterichards** [beberlei/DoctrineExtensions#292]
Using this code in AppKernel.php, gives the above error:

```new \Doctrine\Common\ClassLoader('DoctrineExtensions', './vendor/beberlei/DoctrineExtensions')```

**Comment by stevelacey** [comment]
I imagine you're using Symfony if you have an AppKernel, in which case you don't want to be setting up Doctrine's ClassLoader – I recommend you consult the Symfony docs regarding Doctrine, and the bottom of the DoctrineExtensions README which points you to installing functions in Symfony
