### ISSUE TITLE
Oracles TO_CHAR() supports more than date as arguments and has only *one* required parameter!

### ISSUE THREAD

**Issue by chetzel** [beberlei/DoctrineExtensions#298]
As you can see from the Oracle documentation related to TO_CHAR(), this function supports DATETIME, NUMBER, NCHAR, CLOB and NCLOB as parameter and all of these have *only one required parameter* and up to two optional parameters! The current DQL implementation of the TO_CHAR function *requires two arguments* and does not allow a third parameter, which is wrong.
Please make only the first parameter required and two parameters optional.

**Comment by stevelacey** [comment]
@chetzel please submit a pull request
