### ISSUE TITLE
ClassLoader is deprecated

### ISSUE THREAD

**Issue by YOUR1** [beberlei/DoctrineExtensions#302]
The Doctrine\Common\ClassLoader is deprecated, what is the correct way to load the extensions now?

I'm not using Symfony btw.

**Comment by stevelacey** [comment]
@YOUR1 looks like there's now a Configuration class that is to be used – if this works for you a PR to update our README would be much appreciated 😄

https://www.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/dql-user-defined-functions.html#registering-your-own-dql-functions
