### ISSUE TITLE
Support NULL in IFELSE

### ISSUE THREAD

**Issue by vladyslavstartsev** [beberlei/DoctrineExtensions#309]
I've found that there is no support for NULL in IFELSE.
What I want to is something like this

```
$qb = $this->createQueryBuilder('foo');
$qb
       ->addSelect('IFELSE((foo.status  <> :true), NULL, foo.bar) as baz')
//status can be nullable bool (true/false/null)
```
I get
![image](https://user-images.githubusercontent.com/17382248/48829731-adf3da80-ed7b-11e8-8c32-5d55e6b569f2.png)
```
Doctrine \ ORM \ Query \ QueryException
[Syntax Error] line 0, col 218: Error: Expected Literal, got 'NULL'
```

But with MySQL syntax is completely legal (I mean to but NULL, in the IF)

It will be very nice to have this feature, because right now I need to make 

```
$qb
       ->addSelect('IFELSE((foo.status  <> :true), \'-1\', foo.bar) as baz')
```

and then iterate over the array and set `null` where values are `-1`

**Comment by stevelacey** [comment]
pull requests welcome
