### ISSUE TITLE
Match Against In Boolean Mode

### ISSUE THREAD

**Issue by Fahani** [beberlei/DoctrineExtensions#310]
Hi there,

For those who want to use :

> MATCH (column) AGAINST (:term IN BOOLEAN MODE)

Remember this extension is expecting 

> MATCH (column) AGAINST (:term BOOLEAN)

I spent quite some time figuring that out. It'd be nice that this extension support it as you would use it in normal SQL, if not, it gets confusing...

Best

**Comment by stevelacey** [comment]
pull requests welcome
