### ISSUE TITLE
Versionable doesn't check versions after the one you revert to see if any other fields changed

### ISSUE THREAD

**Issue by TheChech** [beberlei/DoctrineExtensions#32]
If you change a field in version 2, then change another field in version 3, reverting back to version 1 will leave the current value for the field that was changed later.

If that doesn't make sense, consider this code:

	$page = new App\Model\Page;
	$em->persist($page);
	
	//version 1
	$page->setContent('Test 1');
	$page->setSlug('test1');
	$em->flush();
	
	//version 2
	$page->setSlug('test2');
	$em->flush();
	
	//version 3
	$page->setContent('Test 3');
	$em->flush();

Which creates a page record with two versioned records and then version 3 being the current state of the record.

Now reverting to version 1:

	$vm = new DoctrineExtensions\Versionable\VersionManager($em);
	$vm->revert($page, 1);
	echo $page->getContent();

You'd think that would echo "Test 1". It doesn't. It echoes the current value of content - "Test 3". This is because the database version record only contains version 1's value for slug, as that was changed in version 2. Content was changed in version 3, so version 2's record contains version 2's value for content.

It looks like Versionable is just going straight to version 1 and just assuming that between version 1 and the current version, only slug has changed as that is the only thing in that record. However, in reality, both fields have changed.

**Comment by stevelacey** [comment]
@TheChech sorry the reply is so late, but I'm clearing up this repo now. As I am sure you've worked out by now, the Versionable behaviour is no longer supported and is to be removed in 1.0, the same functionality is now available (and maintained) as part of Doctrine core.
