### ISSUE TITLE
Unable to paginate this query

### ISSUE THREAD

**Issue by glen-84** [beberlei/DoctrineExtensions#48]
```
SELECT t, tp, l
FROM Tournaments_Model_Team t
LEFT JOIN t.teamPlayers tp
LEFT JOIN t.lineups l
WHERE t.isDeleted = FALSE
GROUP BY t
HAVING (
    SELECT COUNT(g)
    FROM Tournaments_Model_MatchSetGame g
    WHERE (g.opponent1 = l OR g.opponent2 = l) AND g.result IS NOT NULL
) = 0
ORDER BY t.createdDateTime DESC
```

**Comment by stevelacey** [comment]
@glen-84 I doubt there was ever enough information here to debug this, but whilst I am happy to merge fixes for the paginator into the 0.3, but it is no longer actively supported – I recommend switching to the paginator available in Doctrine core if you're still having issues.
