### ISSUE TITLE
Paginator doesn't display entities that are linked to other entities of same type

### ISSUE THREAD

**Issue by danielberesh** [beberlei/DoctrineExtensions#58]
I have entities of "Entry".

Many "Entry" are linked to other "entry" by the form of a bidirectional onetoone relationship.

Here is the link:

    /**
    @OnetoOne(targetEntity="Entry", cascade={"remove"}, orphanRemoval=true, inversedBy="entry_setup_by")
    **/
    private $setup_entry;

eg.

    Entry #32 --> no link to any other entry
    Entry #33
    Entry #34 --> Linked to Entry #33

In this situation only Entry #32 and Entry #33 show up. 

This gives all entries:

    $dql = "SELECT e FROM SSMURBS\Entry e";
    $query = $em->createQuery($dql);
    $entries = $query->getResult();

This does not:

    $dql = "SELECT e FROM SSMURBS\Entry e";
    $query = $em->createQuery($dql);
    $result_count = Paginate::getTotalQueryResults( $query ); // Step 1
    $paginateQuery = Paginate::getPaginateQuery( $query , 0, 20 ); // Step 2 and 3
    $entries = $paginateQuery->getResult();

Am I doing something wrong?

**Comment by stevelacey** [comment]
@danielberesh I am happy to merge fixes for the paginator into the 0.3, but it is no longer actively supported – I recommend switching to the paginator available in Doctrine core if you're still having issues.
