### ISSUE TITLE
phpunit 3.6

### ISSUE THREAD

**Issue by cbou** [beberlei/DoctrineExtensions#74]
I have a problem with phpunit 3.6:

```
phpunit -c app src/Pidoco/WebshopBundle/Tests/IntegrationTests/CheckoutTest.php 
```

```
PHP Warning:  require_once(PHPUnit/Extensions/Database/TestCase.php): failed to open stream: 
No such file or directory in
 /.../vendor/beberlei-DoctrineExtensions/lib/DoctrineExtensions/PHPUnit/DatabaseTestCase.php 
on line 17
```

I checked the repository of phpunit 3.6 and phpunit 3.4

3.6: https://github.com/sebastianbergmann/phpunit/tree/3.6/PHPUnit/Extensions
3.4: https://github.com/sebastianbergmann/phpunit/tree/3.4/PHPUnit/Extensions

phpunit / PHPUnit / Extensions / Database does not exists in 3.5 and 3.6 anymore.
Should I install something else ?

**Comment by stevelacey** [comment]
I just fixed the tests and set up Travis
