### ISSUE TITLE
paginate a query with count in select

### ISSUE THREAD

**Issue by Elexy** [beberlei/DoctrineExtensions#77]
Hi,

I am trying to do a query along these lines through the paginator:
```$query = $repository->createQueryBuilder('m')
        ->select('m.id, COUNT(m.foo), m.bar')
        ->groupBy ('m.bar')
        ->getQuery();```

when I run it without the paginator it gives me the number of bar's per foo, as excpected, but through the paginator I always get '1' as a count of foo per bar.
What am I doing wrong?

**Comment by stevelacey** [comment]
@Elexy I am happy to merge fixes for the paginator into the 0.3, but it is no longer actively supported – I recommend switching to the paginator available in Doctrine core if you're still having issues.
