### ISSUE TITLE
MatchAgainst throwing invalid parameter number

### ISSUE THREAD

**Issue by ulugbekenuygun** [beberlei/DoctrineExtensions#78]
MatchAgainst extension of Doctrine is throwing "invalid parameter number: number of bound variables does not match number of tokens" exception 

I am using this extension with Symfony2

here is my dql
<code>
$query = $this->getDoctrine()->getEntityManager()->createQuery("
                    SELECT n, h FROM HotelBundle:HotelName n
                    JOIN n.hotel h
                    WHERE MATCH (n.name) AGAINST (?1 BOOLEAN) > 0
                    ORDER BY h.name
");

$query->setParameters(array(1 => $params)); //params is '+rixos'

$hotels = $query->getResult();
</code>

Symfony2 Exception Log show:
1. in /var/www/hotel/vendor/doctrine/lib/Doctrine/ORM/Query/QueryException.php at line 62
<code>

```
public static function invalidParameterNumber()
{
    return new self("Invalid parameter number: number of bound variables does not match number of tokens");
}
public static function invalidParameterFormat($value)
```

</code>
2. in /var/www/hotel/vendor/doctrine/lib/Doctrine/ORM/Query.php at line 240
<code>
        $paramMappings = $this->_parserResult->getParameterMappings();
        if (count($paramMappings) != count($this->_params)) {
            throw QueryException::invalidParameterNumber();
        }
        list($sqlParams, $types) = $this->processParameterMappings($paramMappings);
</code>

<b>I did a little debugging</b> and saw that $paramsMapping array is <b>Empty</b> whereas $this->_params is array(1) { [1]=> string(6) "+rixos" }

But when used <b>without setParameters</b> function <b>I can get correct results</b>
working example:
<code>
$query = $this->getDoctrine()->getEntityManager()->createQuery("
                    SELECT n, h FROM HotelBundle:HotelName n
                    JOIN n.hotel h
                    WHERE MATCH (n.name) AGAINST ('{$params}' BOOLEAN) > 0
                    ORDER BY h.name
");

//$query->setParameters(array(1 => $params)); //params is '+rixos'

$hotels = $query->getResult();
</code>

Might it be Doctrine's bug 'cause of losing paramsMapping or totally user exception ???

**Comment by stevelacey** [comment]
@ulugbekenuygun did you ever make any progress fixing this, I realise it was a while a go, I am just trying to tidy up the issues/PR's. Thanks!

**Comment by ulugbekenuygun** [comment]
@stevelacey As far as I remember I did not fix this, just had to use Sphinx for text search.

**Comment by stevelacey** [comment]
I am going to close this as very very inactive 😅 pull requests welcome as always
