### ISSUE TITLE
PHPUnit getEntityManager() lead assertion number to be wrong

### ISSUE THREAD

**Issue by sliver** [beberlei/DoctrineExtensions#9]
Every getEntityManager(), the number of assertions is increase by one. The number becomes not precise.

**Comment by stevelacey** [comment]
@sliver @fprochazka  I realise this was a while ago, but just cleaning up this repo. I am happy to merge fixes for the PHPUnit stuff into the 0.3, but it is no longer actively supported – I recommend switching to the recommendations for testing provided in Doctrine core if you're still having issues.
