### ISSUE TITLE
mode parameter for Week ?

### ISSUE THREAD

**Issue by patie** [beberlei/DoctrineExtensions#92]
http://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_week

i need set week mode parameter for 1. 

```
WEEK(date,1);
```

whats about this feature ? thanks

**Comment by webdevilopers** [comment]
:+1:

**Comment by stevelacey** [comment]
I think this got fixed at some point, there's a mode toggle in master now either way.
