### ISSUE TITLE
How to use LIKE inside IF?

### ISSUE THREAD

**Issue by vadzzim** [beberlei/DoctrineExtensions#93]
Is it possible somehow use "SELECT IF( value LIKE '%something%' , 1, 0) AS flag FROM table" with DQL?

There is https://github.com/beberlei/DoctrineExtensions/blob/master/lib/DoctrineExtensions/Query/Mysql/IfElse.php#L30

But how change it, so the $this->expr[0] can be ConditionalExpression or LikeExpression or even mixed...

**Comment by stevelacey** [comment]
Relates to https://github.com/beberlei/DoctrineExtensions/issues/132
