### ISSUE TITLE
Field function little typo

### ISSUE THREAD

**Issue by ASKozienko** [beberlei/DoctrineExtensions#94]
https://github.com/beberlei/DoctrineExtensions/blob/master/lib/DoctrineExtensions/Query/Mysql/Field.php

contains duplicate section 

```php
namespace DoctrineExtensions\Query\Mysql;

use Doctrine\ORM\Query\AST\Functions\FunctionNode,
    Doctrine\ORM\Query\Lexer;
```

**Comment by stevelacey** [comment]
Resolved in https://github.com/beberlei/DoctrineExtensions/commit/30eef8629952a3f187a1f88aa0c9b97759b963fa?diff=unified
